version: '3.9'

services:
    nginx:
        image: 'nginx:latest'
        container_name: nginx
        restart: always
        ports:
            - "${APP_PORT}:80"
            - "443:443"
        tty: true
        volumes:
            # - ./:/var/www
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        volumes_from:
            - app
        networks:
            - app-network
        links:
            - app
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            args:
                user: "${USER}"
                uid: "${UID}"
        restart: always
        image: app
        tty: true
        hostname: app
        container_name: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        ports:
            - "9000:9000"
        networks:
            - app-network
        links:
            - mysql
            - redis
        depends_on:
            - mysql
            - redis
            - phpmyadmin
    mysql:
        image: 'mysql:latest'
        container_name: mysql
        hostname: mysql
        restart: always
        tty: true
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'data-mysql:/var/lib/mysql'
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        tty: true
        links:
            - mysql:mysql
        ports:
            - "8081:80"
        environment:
            PMA_HOSTS: mysql:${DB_PORT}
            PMA_PORT: 3008,3007,3006
            PMA_USER: 'root'
            PMA_PASSWORD: '${DB_PASSWORD}'
            PMA_ARBITRARY: 1
        networks:
            - app-network
        depends_on:
            - mysql
    redis:
        image: 'redis:latest'
        container_name: redis
        restart: always
        tty: true
        hostname: redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'data-redis:/data'
        networks:
            - app-network
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping", "-p${REDIS_PASSWORD}" ]
            retries: 3
            timeout: 5s
networks:
    app-network:
        driver: bridge
volumes:
    data-mysql:
        driver: local
    data-redis:
        driver: local
