const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
    SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
    SET_INFO_PAGE: "SET_INFO_PAGE",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
    SET_SIDE_BAR: "SET_SIDE_BAR",
    SET_CONFIG: "SET_CONFIG",
    SET_NOTIFY: "SET_NOTIFY",
    CLEAR_NOTIFY: "CLEAR_NOTIFY",
    SET_TOASTYFY: "SET_TOASTYFY",
    CLEAR_TOASTYFY: "CLEAR_TOASTYFY",
    //admin
    SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
    CLEAR_ACCESS_TOKEN: "CLEAR_ACCESS_TOKEN",
    SET_REFRESH_TOKEN: "SET_REFRESH_TOKEN",
    CLEAR_REFRESH_TOKEN: "CLEAR_REFRESH_TOKEN",

    PROCESS_LOGOUT: "PROCESS_LOGOUT",
    SET_ADMIN: "SET_ADMIN",
    UNSET_ADMIN: "UNSET_ADMIN",
    //user
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    USER_INFO: "USER_INFO",
    USER_SIGN_OUT: "USER_SIGN_OUT",
});

export default actionTypes;
